name: valo_hub
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for handling API requests and network calls.
  dio: ^5.7.0

  # For storing small amounts of data locally (key-value pairs).
  shared_preferences: ^2.3.2

  # Lightweight and fast NoSQL database for local storage.
  hive: ^2.2.3

  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_flutter: ^1.1.0

  # Efficiently caches and loads images from the network.
  cached_network_image: ^3.4.1

  # State management solution using the BLoC (Business Logic Component) pattern.
  flutter_bloc: ^8.1.6

  # Automatically generates native splash screens for both Android and iOS.
  flutter_native_splash: ^2.4.1

  # Helps with responsive UI by adapting to different screen sizes and pixel densities.
  flutter_screenutil: ^5.9.3

  # A service locator for dependency injection and managing app-wide objects.
  get_it: ^7.7.0

  # Audio playback library supporting various formats and platforms.
  just_audio: ^0.9.40

  # Flutter plugin for displaying inline video with other Flutter widgets on Android, iOS, and web.
  video_player: ^2.9.1

  # A video player for Flutter with Cupertino and Material play controls
  chewie: ^1.8.5

  # Classes and helper functions that support JSON code generation via the `json_serializable
  json_annotation: ^4.9.0

  path_provider: ^2.1.4

  intl: ^0.18.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.12

  # Automatically generate code for converting to and from JSON
  json_serializable: ^6.8.0

  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
